version: "3.0"

services:

  seafile_mysql_server:
    container_name: seafile_mysql
    image: mariadb
    volumes:
      - ./configs/mysql:/etc/mysql/conf.d/
      - ./data/mysql:/var/lib/mysql/
      - ./entrypoints/mysql:/docker-entrypoint-initdb.d/
      - ./dump/mysql:/home/
    environment:
      - DB_ROOT_PASSWD=123456
      - MYSQL_ROOT_PASSWORD=123456
    networks:
      - seafile-privite

  seafile_core_server:
    container_name: seafile_server
    image: seafileltd/seafile-mc
    ports:
      - 18000:80
      - 18080:8080
      - 14430:443
    volumes:
      - ./data/seafile-data:/shared
    environment:
      - DB_HOST=seafile_mysql_server
      - DB_ROOT_PASSWD=123456
      - TIME_ZONE=Etc/UTC
      - SEAFILE_ADMIN_EMAIL=1542874601@qq.com
      - SEAFILE_ADMIN_PASSWORD=glyz205070410
      - SEAFILE_SERVER_LETSENCRYPT=false
      - SEAFILE_SERVER_HOSTNAME=0.0.0.0
    depends_on:
      - seafile_mysql_server
    networks:
      - seafile-privite

networks:
  seafile-privite:
